---
# tasks file for base
- name: Ensure selinux-policy is installed
  dnf:
    name: selinux-policy
    state: present
- name: Ensure LibSEManage is installed
  dnf:
    name: python3-libsemanage
    state: present

- name: Disable SELinux
  selinux:
    state: disabled

- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'