---
# defaults file for 389_ds
dirsrv_state: latest
dirsrv_fqdn: "ldap.cloud.skyline.lan"
dirsrv_password: "password"
dirsrv_rootdn: "cn=Directory Manager"
dirsrv_hostname: "{{ dirsrv_fqdn.split('.')[0] }}"
dirsrv_suffix: "dc={{ dirsrv_fqdn.split('.')[-2] | default(389) }},dc={{ dirsrv_fqdn.split('.')[-1] }}"

__dirsrv_packages:
  - 389-ds
  #  - 389-console
  #  - 389-admin
  - ldap-utils

dirsrv_service_name: dirsrv
dirsrv_group: dirsrv
dirsrv_user: dirsrv
dirsrv_setupdsadmin: setup-ds-admin


# Administration server
dirsrv_admin_password: "{{ dirsrv_password }}"
dirsrv_admin_domain: "{{ dirsrv_fqdn.split('.')[1:] | join('.') }}"

