---
- name: Converge
  hosts: all
  vars:
    - GLOBAL_PASSWD: molecule1234
  tasks:
    - name: "Include Base"
      include_role:
        name: "base"
    - name: "Include ldap"
      include_role:
        name: "ldap"
