---
# tasks file for dnsmasq
- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: dnsmasq

- name: Copy Devops Hosts file
  template:
    src: devops-hosts.j2
    dest: /etc/devops-hosts
  notify: restart dnsmasq
  tags: dnsmasq

- name: Set configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq