- name: Install 389 Directory Server
  apt:
    name: 389-ds
    state: present
    update_cache: no

- name: Push Setup file
  template: src=templates/dirsrv.inf dest=/tmp/dirsrv.inf

- name: Setup 389 DS vis /usr/share/dirsrv/setup-ds.pl 389-ds | setup-ds-admin.pl | Execute | {{ dirsrv_hostname }} | {{ dirsrv_fqdn }} | {{ dirsrv_suffix }}
  shell: /usr/sbin/{{ dirsrv_setupdsadmin }} --silent --file=/tmp/dirsrv.inf --logfile=/tmp/389install.log creates=/etc/dirsrv/slapd-{{ dirsrv_hostname }}/dse.ldif

- name: Enable 389 DS Service
  service:
    name: "{{ dirsrv_service_name }}.target"
    state: started
    enabled: yes
